version: 2.0

jobs:
  build:
    docker:
      - image: gcc:latest
    working_directory: ~/work
    steps:
      - checkout
      - run: make
      - run: ./dump
      - run:
          command: ls
          when: always
