version: 2.0

jobs:
  build:
    docker:
      - image: gcc:latest
    working_directory: ~/work
    steps:
      - checkout
      - run: make
      - run: |
        ulimit -c unlimited
        ./dump
      - run:
          command: ls
          when: always
      - store_artifacts:
          path: ~/work
